---
- name: Secure sudo for deploy
  hosts: all
  become: true

  vars_files:
    - ./files/secret.yml

  tasks:
    - name: Ensure user 'deploy' has a password set
      ansible.builtin.user:
        name: deploy
        password: "{{ user_password_hash }}"
        update_password: on_create
        groups: sudo
        append: true
        state: present

    - name: Require password for deploy sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/deploy
        create: true
        regexp: '^deploy\s+ALL='
        line: 'deploy ALL=(ALL) ALL'
        validate: '/usr/sbin/visudo -cf %s'
