---
- name: Deploy nginx new websidan
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/example.internal/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload nginx
